version: "3.8"
services:
    nginx:
        container_name: ee-nginx
        build: ./docker/nginx
        command: nginx -g "daemon off;"
        links:
            - php
        ports:
            - "80:80"
        volumes:
            - ./logs/nginx:/var/log/nginx
            - .:/var/www/html/project
    php:
        container_name: ee-php
        build: ./docker/php
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www/html/project
        working_dir: /var/www/html/project

    composer:
        platform: linux/amd64
        container_name: ee-composer
        image: composer/composer
        volumes:
            - .:/var/www/html/project
        working_dir: /var/www/html/project
        command: sh -c "composer install"

    node:
        container_name: ee-node
        image: alpine:3.18
        volumes:
            - .:/var/www/html/project
        working_dir: /var/www/html/project
        command: sh -c "apk add --no-cache nodejs npm && npm install"

    nodeServer:
        container_name: ee-nodeServer
        image: alpine:3.18
        ports:
            - "5173:5173"
        volumes:
            - .:/var/www/html/project
        working_dir: /var/www/html/project
        command: sh -c "apk add --no-cache nodejs npm && npm run dev"
        depends_on:
            - node

    mysql:
        platform: linux/x86_64
        image: mysql:8.0.27
        container_name: ee-mysql
        environment:
            MYSQL_DATABASE: project
            MYSQL_ROOT_PASSWORD:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        ports:
            - "3306:3306"
        volumes:
            - mysqlDB:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin:5.1
        container_name: ee-phpmyadmin
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 10000:80

    redis:
        image: redis:4.0
        container_name: ee-redis
        ports:
            - "6379:6379"
        volumes:
            - ./docker/redis/log:/log
            - ./docker/redis/data:/data
        healthcheck:
            retries: 3
            timeout: 5s


    migrate-seed:
        build: ./docker/php
        volumes:
            - .:/var/www/html/project
        working_dir: /var/www/html/project
        command: sh -c "chown -R www-data:www-data storage bootstrap/cache && php artisan storage:link && php artisan migrate && php artisan db:seed"
        depends_on:
            - composer
            - mysql

    tests:
        build: ./docker/php
        volumes:
            - .:/var/www/html/project
        working_dir: /var/www/html/project
        command: sh -c "php artisan test"
        depends_on:
            - redis

# image volumes
volumes:
    mysqlDB:
